### ISSUE TITLE
Suggestion:  Using libass-git instead of latest release 

### ISSUE THREAD

**Issue by eko5624** [nyfair/mpv-win64#2]
As the title , libass hasn't released  a new version for a long time , the latest release 0.15.1 (released 2021-05-01) is buggy . So consider my suggestion , thanks .

**Comment by nyfair** [comment]
Can you give me more details about these fixed bugs?

**Comment by eko5624** [comment]
https://github.com/mpv-player/mpv/issues/8874
Like this issue , the latest release hasn't fixed this bug yet . I know it didn't occur on Windows . But I think if using libass-git would be better , IMHO .

**Comment by nyfair** [comment]
Font callback is a quite complicated story, libass is just a library to render subtitle and we can't simply rely on libass to get perfect solution. Your problem is mainly caused by NextFire's build script, IMHO. 

Font choosing is handled by fontconfig on linux and many subsystems like brew which was the one NextFire used. NextFire doesn't shipped his build with default fonts.conf. if you don't install brew and update brew's fontconfig setting, then all missing font such as 方正黑体_GBK will be fallback to macOS's default font Helvetica which contains no CJK glyph.

The [https://github.com/libass/libass/commit/b9f34688f6ef1988136ba5e90a91ae8ac9b8a55f](commit) on 2021/05/13 from libass is just a workaround to iterate all fonts within font family. Suppose if you are watching a movie with Japanese subtitle and your OS is on Chinese locale and Sans font family is defined by the following order
1. Latin Font - Tahoma
2. GB2312 Font - KaiTi
3. GBK Font - Simsun
4. CJK Font - Microsoft Yahei
The subtitle will be rendered by 4 different fonts and the result will be quite awful. You know this is not a joke and it is even the default Windows XP sans-serif fontconfig fallback setting

For my build, this is another story since I'm not a fan of fontconfig and I don't use that.
Anyway, I think you can still get a better solution without libass's workaround patch. For example, shinchiro ships his mpv build with Noto Sans and specify fonts.conf to always fallback to that for missing fonts. You can steal his fonts.conf from https://github.com/shinchiro/mpv-winbuild-cmake/blob/9dd14a50369ee31c7494f49cc9e7c7adb4dbffb2/packages/mpv/mpv/fonts.conf and modify Noto Sans to other macOS font like Hiragino Sans GB or install Noto Sans yourself

**Comment by eko5624** [comment]
I get it ,thanks for your explanation ~

**Comment by eko5624** [comment]
Forget the issue, just one request:  Can you teach me how to write yml: libass  and pkgbuild: libass-git . I write them , but run errors like this .

If you upload the two files here would be great . Thanks in advance ~

![E2C12A0F-ACA5-4911-8301-0290CB835C17](https://user-images.githubusercontent.com/84926938/126756012-14822359-c8e7-493a-bfe6-4a1746e20c1a.png)

**Comment by nyfair** [comment]
[https://github.com/eko5624/mpv-win64/blob/master/.github/workflows/libass-git.yml#L31]()
This line should be
```
C:\msys64\usr\bin\bash -lc 'cd /d/a/mpv-win64/mpv-win64/libass-dev; PATH=/usr/bin:/opt/bin:/d/ucrt64/bin PKG_CONFIG_PATH=/opt/lib/pkgconfig makepkg -p PKGBUILD-git
```

**Comment by eko5624** [comment]
Thank you verrrrrrrrry much. It works! Your building scripts are much more simpler than shinchiro's .   Great job !!
